tp3/config/routes.rb
Rails.application.routes.draw do
  
  resources :posts

  get 'users' => 'users#index'

  post 'users/new' => 'users#create'

  get 'users/export' => 'users#export'

  root 'pages#home'

  get 'pages/about' => 'pages#about'

  get 'pages/random/(:times)' => 'pages#random'
end

tp3/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  def formatted_message(shout:false)
    "#{user.name} said: #{shout ? message.upcase : message}"
  end
end

tp3/app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :post
  validates :url, format: { with: /http:\/\/[\w]*\.[\w]*\/[\w]*\.(jpg|gif)/ }

  def self.all_urls
    select(:url).map(&:url)
  end

  def file
    return nil unless valid?
    url.split("/").last
  end

  def file_format
    return nil unless valid?
    file.split(".").last
  end
end

tp3/app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { where(published: true) }
  belongs_to :user
  has_many :comments
  has_many :photos

  validates :user_id, presence: true
  scope :published, -> { where(published: true) }

  before_create :upcase_title

  def upcase_title
    if title
      self.title =  title.slice(0,1).capitalize + title.slice(1..-1)
    end
  end

  def length
    message.blank? ? nil : message.size
  end

  def unpublish!
    self.update_attribute(:published, false)
  end

  def self.unpublish_all
    update_all(published: false)
  end
end

tp3/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, format: { with: /\w*@\w*\.\w*/ }, uniqueness: true

  has_many :posts
  has_many :comments

  has_many :commented_posts, through: :comments, source: :post

  def self.export(format:)
    if format == :json
      User.all.inject([]) do |res, u|
        res << { id: u.id, name: u.name, email: u.email }
      end.to_json
    else
      raise ArgumentError
    end
  end
end

tp3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tp3/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  	render :layout => false
  end

  def random
  	if !params[:times].blank?
  		@times = params[:times].to_i
	end
  end
end

tp3/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
  	@posts = Post.where(published: true)
  end

  def new
  	@users = User.all
  	@post = Post.new
  end

  def show
  	@post = Post.find_by_id(params[:id]) or not_found
  end

  def not_found
  	render :status => 404
  end

  def create 
  	@post = Post.new(post_params)

  	if @post.save
  		redirect_to posts_path
	else
		flash[:error] = "User can't be blank"
		render action: "new"
	end
  end

  def post_params
  	params.require(:post).permit(:user_id, :message)
  end

  def edit
  	@post = Post.find_by_id(params[:id])
  end

  def update
  	@post = Post.find_by_id(params[:id]).update_attributes(:message => params[:post][:message])
  end

end

tp3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all

  	@user = User.new
  end

  def create
  	
  	user_params = params.require(:user).permit(:name, :email)
  	@user = User.new(user_params)

  	if @user.save
  		flash[:notice] = "User successfully registered"
  		redirect_to users_path
    end
  end

  def export
  	render json: User.select(User.attribute_names - ['created_at', 'updated_at'])
  end
end

tp3/app/helpers/application_helper.rb
module ApplicationHelper
end

tp3/app/helpers/pages_helper.rb
module PagesHelper
end

tp3/app/helpers/posts_helper.rb
module PostsHelper
end

tp3/app/helpers/users_helper.rb
module UsersHelper
end

tp3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TP3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tp3/app/views/pages/about.html.erb
This is a class about Ruby on Rails

tp3/app/views/pages/home.html.erb
"Welcome on the homepage!"

tp3/app/views/pages/random.html.erb
<% if @times && @times != 0 %>
	<% @times.times do |time| %>
		<div><%= time %></div>
	<% end %>
<% else %>
	<p>No valid param</p>
<% end %>

tp3/app/views/posts/edit.html.erb
<h1>Edit post <%= @post.id %></h1>

<%= form_for @post, url: {action: "edit"} do |f| %>

	<%= text_area_tag(:message, @post.message, size: "24x6") %>

	<%= f.submit "Edit post" %>
<% end %>

tp3/app/views/posts/index.html.erb
<h1>Coucou les posts</h1>

<% @posts.each do |post| %>
	<div><p><%= post.user.name %> wrote <%=  post.message %></p></div>
<% end %>

<%= link_to "New post", new_post_path %>

tp3/app/views/posts/new.html.erb
<% if !@users.blank? %>
	<h1>Create a new post!</h1>

	<%= form_for @post, url: {action: "create"} do |f| %>

		<%= @post.errors.full_messages.join(",") %>

		<%= text_area_tag(:message, "Hi, nice site", size: "24x6") %>

		<%= select_tag "users", options_from_collection_for_select(@users, "id", "name") %>

		<%= f.submit "Create post" %>
	<% end %>
<% else %>
	<h1>No users present</h1>
<% end %>

<% if flash[:error] %>
	<div class="error"><%= flash[:error] %></div>
<% end %>

tp3/app/views/posts/show.html.erb
<% if @post %>
	<h1>Post by <%= @post.user.name %></h1>

	<p><%= @post.message %></p>
<% end %>

tp3/app/views/users/create.html.erb
<%= @user.errors.full_messages.join(",") %>

tp3/app/views/users/index.html.erb
<h1>All Users</h1>

<% if !@users.blank? %>
	<% @users.each do |user| %>
		<p><%= user.name %></p>
	<% end %>
<% end %>

<br/>

<h2>Create a new user</h2>

<%= form_for @user, url: {action: "create"} do |f| %>
	<%= f.text_field :name %>
	<%= f.email_field :email %>
	<%= f.submit "Create" %>
<% end %>

<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>